language: python
cache: pip
python:
  - 3.6
install:
  - pip install .
script:
  - make
notifications:
  email:
    - xiaoxiang.cn@gmail.com
    - xiaoxiang_cn@qq.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cf729254f8369ea4f7c3
    on_success: change
    on_failure: always
    on_start: never
deploy:
  provider: pypi
  on:
    tags: true
    repo: zhouxiaoxiang/oriole-service
  distributions: bdist_wheel sdist
  user: zhouxiaoxiang
  password:
    secure: Xp9njkAnNPIjxH4s6FpxOJPAyTFrKYDU65nt9lhMDyJsz3M2sGaFijrRSDXMaoEMkzhvJ1Ij3tqvse//MP9ga11O0snixj9NYI/jym/MLkM/0Qg9FtI1NA2Rnz+q/VA27t36WVP3tjhlH1toTxLqli9aKpIFYnwJFz9qQ2NNTfHNH3Rw1QZUz3zDU/QqktYQLeNbwy8kwXg5x9INlPepv9G/GL437ch2CscZylUWfZ12Th6U1P3VTNFEUfWCcblFkNjfuwrPQQ9PmgpyE00+ak5Ayo7Cijh/UN5do8rIKB/rc/EIvIFy0aMqLBrucRB+QsHCjkWk0pZWilHBcJBv0j43Z8wk5Y35Y1yv1ZL3RD9hpK2gqzQkXAaJ2HnxsarvyMSubHHEq8cTtC42IgzEf+FxJdp9Lw6IRBEDKaimyHhNiE0guoeNDqvSsTAgy0q2WGOTs+3W2cRr90pWAEO7cEhtHhHFn2RBrKKIC6kLOB7QyyPERKYwtwt96Q+rxd8nXk60aG+OdeEAaoD/ezUujpqMuJI47DUi5R8RX+mccVpsO5kNGwuU2z948c3FyB+pEzGznqkNRETBqecTBqm4WA/RGiUZnohLrsu7MSO8VGaqEmg+G3AdEZgj7pvfH++t/QfXioilxNCX1TTgBicGQJLHLESA+XE1hHDuL7AEUqI=
